name: Docker Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: express-rest-auth
      run: |
        docker build . -t botprzemek/express-rest-auth
    - name: Push the Docker image
      working-directory: express-rest-auth
      run: |
        docker push botprzemek/express-rest-auth
